### ISSUE TITLE
test background task to calculate hourly averages

### ISSUE THREAD

**Issue by silvioheinze** [luftdaten-at/luftdaten-api#18]

**Comment by n11ik** [comment]
Ja mache ich.

**Comment by n11ik** [comment]
Ich habe jetzt mal einen normalen view erstellt, weil die postgresql datenbank von sich aus keine IMVs unterstützt, falls es später zu performance Problemen kommen sollte können wir andenken z.B. diese [erweiterung](https://github.com/sraoss/pg_ivm) zu verwenden.

Ich glaube das ein normaler view für unsere momentanen Datenmängen völlig ausreichend ist.

@silvioheinze 
Soll ich auch gleich ein get auf der api einrichten, damit man die mittelwerte abfragen kann, sonst würde ich das issue schließen.

**Comment by silvioheinze** [comment]
Ah, super, das kannte ich noch garnicht!

Schau dir mal die Geosphere API an (https://dataset.api.hub.geosphere.at/v1/openapi-docs) und überlege, ob es einen neuen Endpunkt braucht dafür oder ob es in einen vorhandenen (z.B. /station/historical) integriert werden kann.
