### ISSUE TITLE
Create script to import Sensor.comunity data from Archive

### ISSUE THREAD

**Issue by silvioheinze** [luftdaten-at/luftdaten-api#37]
Die aktuellen Daten werden schon über den background Service importiert. Wie können die fehlenden historischen Daten von den Stationen, welche in der Datenbank sind, importiert werden?

**Comment by n11ik** [comment]
@silvioheinze stimmen die SensorModel ids und die Dimension ids von uns mit denen der SensorCommunity überein?
Im [archive](https://archive.sensor.community) habe ich nur csv Datein gefunden, in denen aber nur die Sensor und Dimensions Namen als string angegeben sind.
Darum müssten wir unsere enums um diese Namen erweitern.
Für die Dimensions ids glaube ich sollte das: https://api.sensor.community/v1/push-sensor-data/ unter options ein vollständige liste sein.
Für die SensorModels habe ich nichts gefunden. Du hast mir mal eine list von Pins und der SensorModel Namen geschickt. Korrelieren die pins mit den ids? Wenn ja, könntest du mir bitte nochmal den link zu der list schicken.
